In [1]:
%matplotlib notebook

In [3]:
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import datetime as dt

In [4]:
housing_df = pd.read_csv("Resources/DC_Properties.csv")

C:\Users\freguenet3\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
housing_df.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [6]:
housing_df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [7]:
housing_df.dtypes.head

<bound method NDFrame.head of Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE               float64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT          float64
CENSUS_BLOCK           object
WARD                   object
SQUARE                 object
X                     float64
Y                     float64
QUADRANT               object
dtype: object>

In [8]:
housing_df.count()

Unnamed: 0            158957
BATHRM                158957
HF_BATHRM             158957
HEAT                  158957
AC                    158957
NUM_UNITS             106696
ROOMS                 158957
BEDRM                 158957
AYB                   158686
YR_RMDL                80928
EYB                   158957
STORIES               106652
SALEDATE              132187
PRICE                  98216
QUALIFIED             158957
SALE_NUM              158957
GBA                   106696
BLDG_NUM              158957
STYLE                 106696
STRUCT                106696
GRADE                 106696
CNDTN                 106696
EXTWALL               106696
ROOF                  106696
INTWALL               106696
KITCHENS              106695
FIREPLACES            158957
USECODE               158957
LANDAREA              158957
GIS_LAST_MOD_DTTM     158957
SOURCE                158957
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  106051
STATE                 106051
ZIPCODE               158956
NATIONALGRID          106051
LATITUDE              158956
LONGITUDE             158956
ASSESSMENT_NBHD       158956
ASSESSMENT_SUBNBHD    126406
CENSUS_TRACT          158956
CENSUS_BLOCK          106051
WARD                  158956
SQUARE                158957
X                     158720
Y                     158720
QUADRANT              158720
dtype: int64

In [7]:
housing_df2 = housing_df.drop(["Unnamed: 0", "BLDG_NUM", "NATIONALGRID", "X", "Y"], axis=1)
housing_df2

,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,...,ZIPCODE,LATITUDE,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,QUADRANT
0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,1972,...,20009.0,38.914680,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW
1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,1972,...,20009.0,38.914683,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW
2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,1984,...,20009.0,38.914684,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW
3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,1984,...,20009.0,38.914683,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW
4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,1985,...,20009.0,38.914383,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW
5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,NaN,1972,...,20009.0,38.914331,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW
6,1,0,Warm Cool,Y,2.0,5,2,1917.0,1988.0,1957,...,20009.0,38.914983,-77.041055,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,1972,...,20009.0,38.915408,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
8,3,1,Warm Cool,Y,2.0,7,3,1908.0,2008.0,1967,...,20009.0,38.915017,-77.039903,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
9,1,1,Hot Water Rad,Y,1.0,6,2,1908.0,1979.0,1950,...,20009.0,38.915015,-77.040081,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,1954,...,20009.0,38.914980,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
11,5,0,Hot Water Rad,Y,3.0,16,6,1905.0,NaN,1950,...,20009.0,38.915363,-77.039718,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,1963,...,20009.0,38.914999,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,1963,...,20009.0,38.914997,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
14,3,1,Warm Cool,Y,2.0,5,3,1917.0,2000.0,1967,...,20009.0,38.915038,-77.039716,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,1947,...,20009.0,38.915019,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
16,3,1,Warm Cool,Y,1.0,8,3,1908.0,2006.0,1967,...,20009.0,38.915018,-77.039844,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
17,2,0,Hot Water Rad,N,1.0,6,3,1908.0,1987.0,1957,...,20009.0,38.915017,-77.039961,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
18,3,1,Hot Water Rad,Y,2.0,10,4,1908.0,2006.0,1967,...,20009.0,38.915016,-77.040020,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,1969,...,20009.0,38.915019,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW
20,3,1,Hot Water Rad,Y,1.0,14,5,1880.0,2009.0,1987,...,20009.0,38.911370,-77.033774,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
21,3,0,Forced Air,Y,2.0,12,3,1880.0,2009.0,1969,...,20009.0,38.911368,-77.033838,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
22,1,0,Forced Air,Y,1.0,6,3,1880.0,2010.0,1967,...,20009.0,38.911368,-77.033925,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
23,2,1,Forced Air,Y,1.0,5,3,1880.0,2010.0,1984,...,20009.0,38.911368,-77.033972,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
24,2,1,Hot Water Rad,Y,1.0,8,3,1880.0,2004.0,1967,...,20009.0,38.911319,-77.034070,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
25,1,0,Hot Water Rad,N,1.0,8,4,1880.0,2010.0,1967,...,20009.0,38.911337,-77.034156,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,1960,...,20009.0,38.911736,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
27,3,0,Hot Water Rad,Y,4.0,9,3,1900.0,1963.0,1967,...,20009.0,38.911732,-77.034182,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
28,3,0,Warm Cool,Y,2.0,10,4,1900.0,1960.0,1960,...,20009.0,38.911677,-77.034119,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
29,3,1,Forced Air,Y,2.0,11,3,1900.0,2014.0,1984,...,20009.0,38.911699,-77.034051,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,1993,...,20001.0,38.914279,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,NW
158928,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,2013,...,20001.0,38.914279,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,NW
158929,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,2013,...,20001.0,38.914279,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,NW
158930,2,0,Forced Air,N,NaN,4,2,1900.0,2003.0,1919,...,20001.0,38.912947,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,NW
158931,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,1919,...,20001.0,38.912947,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,NW
158932,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,1919,...,20001.0,38.912947,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,NW
158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,1919,...,20001.0,38.912947,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,NW
158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,1919,...,20001.0,38.912947,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,NW
158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,1919,...,20001.0,38.912947,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,NW
158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,1919,...,20001.0,38.912947,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,NW
158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,1992,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158938,2,0,Warm Cool,Y,NaN,7,4,1992.0,1992.0,1992,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158939,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,1992,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158940,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,1992,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,1992,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,1992,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158943,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,2004,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158944,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,2004,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158945,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158946,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158947,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158948,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158949,1,1,Forced Air,Y,NaN,4,1,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158950,3,0,Forced Air,Y,NaN,5,3,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158951,3,1,Forced Air,Y,NaN,5,3,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,1938,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,1920,...,20001.0,38.911840,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,NW
158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,1965,...,20024.0,38.872953,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,SW
158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,1965,...,20024.0,38.872953,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,SW

In [13]:
housing_df2 = housing_df2[housing_df2.PRICE.notnull()]
housing_df2['PRICE'].count()

98216

In [15]:
housing_df2 = housing_df2[housing_df2.PRICE.notnull()]
residential_df = housing_df2.loc[housing_df2["SOURCE"] == "Residential"]
residential_df['YEAR'] = pd.DatetimeIndex(residential_df['SALEDATE']).year
residential_df['MONTH'] = pd.DatetimeIndex(residential_df['SALEDATE']).month
residential_df2 = residential_df.query("YEAR>1991.0") 
residential_df3 = residential_df2.query("YEAR<2018")
residential_df3['PRICE'].count()

C:\Users\freguenet3\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\freguenet3\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

54752

In [79]:
# residential_df3['YEAR'] = pd.DatetimeIndex(residential_df3['SALEDATE']).year
# residential_df3['MONTH'] = pd.DatetimeIndex(residential_df3['SALEDATE']).month
# residential_df3.head(5)

C:\Users\freguenet3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\freguenet3\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,QUADRANT,YEAR,MONTH
0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,1972,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW,2003,11
2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,1984,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW,2016,6
3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,1984,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW,2006,7
5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,NaN,1972,...,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,NW,2010,2
7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,1972,...,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,NW,2011,9

In [80]:
NE = residential_df3[["YEAR", "PRICE", "QUADRANT"]]
price_evolution_by_year

        YEAR      PRICE QUADRANT
0       2003  1095000.0       NW
2       2016  2100000.0       NW
3       2006  1602000.0       NW
5       2010  1950000.0       NW
7       2011  1050000.0       NW
14      2011  1325000.0       NW
16      2010  1240000.0       NW
19      2001   592250.0       NW
20      2016    33232.0       NW
22      2006   907400.0       NW
23      2012  1065000.0       NW
24      2012  1100000.0       NW
25      1996    20000.0       NW
27      2005   703700.0       NW
29      2013  1210000.0       NW
32      1999   130500.0       NW
37      1997   339500.0       NW
40      2006  1050000.0       NW
41      2016  1550000.0       NW
42      2015  1599900.0       NW
44      2017  1700000.0       NW
45      2001   450000.0       NW
46      2011   846000.0       NW
48      1999   348500.0       NW
50      2009   849000.0       NW
52      2006  1312000.0       NW
54      1997   390000.0       NW
55      2004   772500.0       NW
58      2010   499000.0       NW
59      2000   216000.0       NW
...      ...        ...      ...
106629  1994    80000.0       SW
106630  1993    60700.0       SE
106631  2010   180000.0       SE
106632  2008   285000.0       SE
106633  1998    67100.0       SE
106637  1993    73000.0       SE
106638  1997   109950.0       SE
106642  2009    66675.0       SE
106645  2012   180000.0       SE
106646  2005   193000.0       SE
106650  2016   336000.0       SE
106651  1995    90000.0       SE
106653  2007    90000.0       SE
106654  2008   106000.0       SE
106656  2014   227000.0       SE
106657  2008   140496.0       SE
106662  2001   120000.0       SE
106663  1996   109256.0       SE
106664  2013   230000.0       SE
106666  2012   215000.0       SE
106668  2005   205000.0       SE
106672  2002   100000.0       SW
106673  2002   103000.0       SW
106682  2000   118000.0       SW
106683  2000        1.0       SW
106687  2004    95000.0       SW
106688  2016   185000.0       SW
106692  2012   100000.0       SW
106694  2017   215000.0       SW
106695  2017   140000.0       SW

[54752 rows x 3 columns]

In [18]:
NW1 = residential_df3.loc[residential_df3["QUADRANT"] == "NW" , ['QUADRANT','PRICE','YEAR']]
NW2 = NW1.groupby('YEAR')['PRICE'].mean().round(0)
NW2
                          
# ave_price_evolution_since92_NW = price_evolution_since92_NW.groupby("YEAR")["PRICE"].mean().round(0)
# ave_price_evolution_since92_NW_df = pd.DataFrame(ave_price_evolution_since92_NW)
# # ave_price_evolution_since92_NW_df.plot()
# ave_price_evolution_since92_NW_df

YEAR
1992.0     320172.0
1993.0     284623.0
1994.0     284057.0
1995.0     292569.0
1996.0     300853.0
1997.0     321744.0
1998.0     302078.0
1999.0     334111.0
2000.0     374810.0
2001.0     424761.0
2002.0     490592.0
2003.0     580597.0
2004.0     661435.0
2005.0     785447.0
2006.0     820582.0
2007.0     885203.0
2008.0     819722.0
2009.0     769656.0
2010.0     835955.0
2011.0     856319.0
2012.0     873919.0
2013.0     978846.0
2014.0     998252.0
2015.0    1033005.0
2016.0    1058664.0
2017.0    1112038.0
Name: PRICE, dtype: float64

In [19]:
price_evolution_by_year = pd.DataFrame(residential_df3[["YEAR", "PRICE", "QUADRANT"]])


# clean_price_evolution_since92 = price_evolution_since92.dropna(axis=1, how='any')
# price_evolution_since92_df = pd.DataFrame(clean_price_evolution_since92)
price_evolution_since92_NW = price_evolution_since92.loc[price_evolution_since92["QUADRANT"] == "NW"]
ave_price_evolution_since92_NW = price_evolution_since92_NW.groupby("YEAR")["PRICE"].mean().round(0)
ave_price_evolution_since92_NW_df = pd.DataFrame(ave_price_evolution_since92_NW)
ave_price_evolution_since92_NW_df.plot()

price_evolution_since92_NE = price_evolution_since92.loc[price_evolution_since92["QUADRANT"] == "NE"]
ave_price_evolution_since92_NE = price_evolution_since92_NW.groupby("YEAR")["PRICE"].mean()
ave_price_evolution_since92_NE_df = pd.DataFrame(ave_price_evolution_since92_NE)
ave_price_evolution_since92_NE_df.plot()

price_evolution_since92_SW = price_evolution_since92.loc[price_evolution_since92["QUADRANT"] == "SW"]
ave_price_evolution_since92_SW = price_evolution_since92_NW.groupby("YEAR")["PRICE"].mean()
ave_price_evolution_since92_SW_df = pd.DataFrame(ave_price_evolution_since92_SW)
ave_price_evolution_since92_SW_df.plot()

price_evolution_since92_SE = price_evolution_since92.loc[price_evolution_since92["QUADRANT"] == "SE"]
ave_price_evolution_since92_SE = price_evolution_since92_NW.groupby("YEAR")["PRICE"].mean()
ave_price_evolution_since92_SE_df = pd.DataFrame(ave_price_evolution_since92_SE)
ave_price_evolution_since92_SE_df.plot()

# ax = df1.plot()
# df2.plot(ax=ax)




# grouped_since2000 = price_evolution_since2000.groupby(["QUADRANT", "YEAR"])["PRICE"].mean()
# grouped_since2000_df = pd.DataFrame(grouped_since2000)
# grouped_since2000_df.plot()
# clean_price_evolution_since92.plot(x="YEAR", y= "PRICE")

NameError: name 'price_evolution_since92' is not defined

In [60]:
price_evolution_by_year

          YEAR      PRICE QUADRANT
0       2003.0  1095000.0       NW
2       2016.0  2100000.0       NW
3       2006.0  1602000.0       NW
5       2010.0  1950000.0       NW
7       2011.0  1050000.0       NW
8       2018.0  1430000.0       NW
14      2011.0  1325000.0       NW
16      2010.0  1240000.0       NW
19      2001.0   592250.0       NW
20      2016.0    33232.0       NW
22      2006.0   907400.0       NW
23      2012.0  1065000.0       NW
24      2012.0  1100000.0       NW
25      1996.0    20000.0       NW
27      2005.0   703700.0       NW
29      2013.0  1210000.0       NW
32      1999.0   130500.0       NW
37      1997.0   339500.0       NW
40      2006.0  1050000.0       NW
41      2016.0  1550000.0       NW
42      2015.0  1599900.0       NW
43      2018.0  1700000.0       NW
44      2017.0  1700000.0       NW
45      2001.0   450000.0       NW
46      2011.0   846000.0       NW
48      1999.0   348500.0       NW
50      2009.0   849000.0       NW
52      2006.0  1312000.0       NW
54      1997.0   390000.0       NW
55      2004.0   772500.0       NW
...        ...        ...      ...
158918  2015.0   839000.0       NW
158919  2015.0   915500.0       NW
158920  2017.0   880000.0       NW
158921  2017.0  1120000.0       NW
158924  2004.0   269000.0       NW
158926  2014.0   385000.0       NW
158928  2017.0   632400.0       NW
158929  2012.0   574000.0       NW
158930  2007.0   365000.0       NW
158931  2005.0   405000.0       NW
158932  2014.0   505000.0       NW
158933  2017.0   520000.0       NW
158934  2017.0   499900.0       NW
158935  2016.0   451000.0       NW
158936  2016.0   564900.0       NW
158938  2015.0   660000.0       NW
158939  2016.0   380000.0       NW
158943  2004.0   539000.0       NW
158944  2016.0   908500.0       NW
158945  2006.0   450000.0       NW
158946  2015.0   485355.0       NW
158947  2008.0   320000.0       NW
158948  2012.0   460000.0       NW
158949  2015.0   550000.0       NW
158950  2015.0   635000.0       NW
158951  2009.0   389000.0       NW
158952  2015.0   399900.0       NW
158953  2013.0   416000.0       NW
158954  2008.0   600000.0       NW
158955  2015.0   215100.0       SW

[98216 rows x 3 columns]